id: 72b7799414b14c41957b8bc9b0c170b1
title: Toh_78-The_Questions_of_Gunaratnasankusumita-v2
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-043-015
  eft-text-version: 1.0.6 2020
